# 应用名称
spring:
  application:
    name: MingChuAPI
  thymeleaf: # THYMELEAF (ThymeleafAutoConfiguration)
    cache: true     # 开启模板缓存（默认值： true ）
    check-template: true # 检查模板是否存在，然后再呈现
    check-template-location: true # 检查模板位置是否正确（默认值 :true ）
    content-type: text/html #Content-Type 的值（默认值： text/html ）
    enabled: true # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    encoding: UTF-8
    mode: HTML5 # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    prefix: classpath:/templates/ # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    suffix: .html

server:
  port: 8091

url:
  liveurl: https://open.andmu.cn/v3/open/api/websdk/player #接口B01 直播返回地址链接



